name: checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: pnpm/action-setup@v2
        with:
          node-version: 18
      - run: pnpm install
      - run: pnpm type:check
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: pnpm/action-setup@v2
        with:
          node-version: 18
      - run: pnpm install
      - run: pnpm lint:check
